<a href="https://colab.research.google.com/github/kajalkumari13/-resume/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
 import torch
 print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU is available!
Using GPU: Tesla T4


In [11]:
a = torch.empty(3,6)

In [7]:
type(a)

torch.Tensor

In [10]:
torch.zeros(3,6)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [12]:
torch.ones(3,6)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [13]:
torch.rand(3,6)

tensor([[0.0983, 0.4124, 0.7736, 0.2478, 0.2682, 0.6074],
        [0.3244, 0.1577, 0.7600, 0.6982, 0.2673, 0.0530],
        [0.8268, 0.1537, 0.4938, 0.4384, 0.5668, 0.5747]])

In [14]:
torch.manual_seed(100)
torch.rand(3,6)

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080, 0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183, 0.9014, 0.9969, 0.7565]])

In [15]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
print("using arange ->", torch.arange(0,10,2))

using arange -> tensor([0, 2, 4, 6, 8])


In [17]:
print("using linspace ->", torch.linspace(0,10,10))

using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [18]:
print("using eye ->", torch.eye(5))

using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [19]:
print("using full ->", torch.full((3,3), 5))

using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


TENSOR SHAPES


In [20]:
x = torch.tensor([[1,2,3], [4,5,6]])

In [21]:
x.shape

torch.Size([2, 3])

In [22]:
torch.empty_like(x)

tensor([[835576112, 835517616,       116],
        [      113,        48,        97]])

In [23]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [30]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

**TENSOR DATA TYPES**

In [26]:
x.dtype

torch.int64

In [27]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [28]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [29]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])